### PR TITLE
Saving to the persistent storage blocks the main queue.

### PR DESCRIPTION
**Pull request by EgorSobko**
Moved work related to saving data into persistent storage to global queue to NOT block the main thread

### CODE REVIEW

**Comment by parfeon** [comment]
Hello @EgorSobko 

Depending from whether Keychain available or not, save will happen `in-memory` or with asynchronous access to Keychain.

In v5 storage will be changed to `plist`, but we may also change save to synchronous, because that information is pretty important, if we will need to help resolve any kind of issues with published messages. If save asynchronous, there is a chance, that during transition to background execution context queue will be frozen. There is a chance to loose data in this case, because user may kill application as next step.

**Comment by EgorSobko** [comment]
Hello @parfeon. What I observed in my project is the situation when users quickly minimize the app(it goes to inactive state) and then open app again(app state becomes active). App receives notification, locks main queue and Watchdog kills it because process takes more than 10 sec. It's either a deadlock or the saving work really takes so much time, don't know for sure.

**Comment by EgorSobko** [comment]
What if we create a sync working queue and process all the work there? Will it be ok? Process will stay sync but we won't have to wait on the main thread anything.

**Comment by parfeon** [comment]
@EgorSobko is there crash log to share?

**Comment by EgorSobko** [comment]
@parfeon 
```Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
Termination Description: SPRINGBOARD, scene-update watchdog transgression: application<com.avast.ios.omnichild>:3476 exhausted real (wall clock) time allowance of 10.00 seconds | ProcessVisibility: Foreground | ProcessState: Running | WatchdogEvent: scene-update | WatchdogVisibility: Foreground | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 16.770 (user 16.770, system 0.000), 12% CPU", | "Elapsed application CPU time (seconds): 0.987, 1% CPU" | )
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x000000019d60a648 semaphore_timedwait_trap + 8
1   libdispatch.dylib             	0x000000019d4d2fb4 _dispatch_sema4_timedwait$VARIANT$armv81 + 64
2   libdispatch.dylib             	0x000000019d4d353c _dispatch_semaphore_wait_slow + 72
3   PubNub                        	0x000000010993b30c 0x109918000 + 144140
4   PubNub                        	0x000000010993b478 0x109918000 + 144504
5   PubNub                        	0x000000010994c7b0 0x109918000 + 214960
6   PubNub                        	0x000000010994d3e8 0x109918000 + 218088
7   CoreFoundation                	0x000000019d78e9ac __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
8   CoreFoundation                	0x000000019d78e9f4 ___CFXRegistrationPost1_block_invoke + 64
9   CoreFoundation                	0x000000019d78dd54 _CFXRegistrationPost1 + 368
10  CoreFoundation                	0x000000019d78da20 ___CFXNotificationPost_block_invoke + 104
11  CoreFoundation                	0x000000019d709d38 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1416
12  CoreFoundation                	0x000000019d78d370 _CFXNotificationPost + 1244
13  Foundation                    	0x000000019dae9cf8 -[NSNotificationCenter postNotificationName:object:userInfo:] + 60
14  UIKitCore                     	0x00000001a181b364 __47-[UIApplication _applicationDidEnterBackground]_block_invoke + 312
15  UIKitCore                     	0x00000001a1220a54 +[UIViewController _performWithoutDeferringTransitionsAllowingAnimation:actions:] + 168
16  UIKitCore                     	0x00000001a181b120 -[UIApplication _applicationDidEnterBackground] + 116
17  UIKitCore                     	0x00000001a0fff0c0 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke_2 + 824
18  UIKitCore                     	0x00000001a1488c00 _UIScenePerformActionsWithLifecycleActionMask + 100
19  UIKitCore                     	0x00000001a0ffecec __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 196
20  UIKitCore                     	0x00000001a0ffe748 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 296
21  UIKitCore                     	0x00000001a0ffeb14 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 728
22  UIKitCore                     	0x00000001a0ffe3d8 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 336
23  UIKitCore                     	0x00000001a10026a8 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke_2 + 160
24  UIKitCore                     	0x00000001a13bc9f8 +[BSAnimationSettings+ 5790200 (UIKit) tryAnimatingWithSettings:actions:completion:] + 824
25  UIKitCore                     	0x00000001a14a1dbc _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 244
26  UIKitCore                     	0x00000001a10023fc __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 136
27  UIKitCore                     	0x00000001a14a1cb8 _UISceneSettingsDiffActionPerformActionsWithDelayForTransitionContext + 100
28  UIKitCore                     	0x00000001a1002268 -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 376
29  UIKitCore                     	0x00000001a0e7ae70 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 636
30  UIKitCore                     	0x00000001a0e799d8 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 248
31  UIKitCore                     	0x00000001a0e7aba8 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 220
32  UIKitCore                     	0x00000001a13dd4d4 -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] + 464
33  FrontBoardServices            	0x00000001a289220c -[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:] + 544
34  FrontBoardServices            	0x00000001a28b8a28 __88-[FBSWorkspaceScenesClient sceneID:updateWithSettingsDiff:transitionContext:completion:]_block_invoke_2 + 120
35  FrontBoardServices            	0x00000001a289c390 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 232
36  FrontBoardServices            	0x00000001a28b895c __88-[FBSWorkspaceScenesClient sceneID:updateWithSettingsDiff:transitionContext:completion:]_block_invoke + 184
37  libdispatch.dylib             	0x000000019d5011cc _dispatch_client_callout + 16
38  libdispatch.dylib             	0x000000019d4db4d0 _dispatch_block_invoke_direct$VARIANT$armv81 + 216
39  FrontBoardServices            	0x00000001a28de210 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 40
40  FrontBoardServices            	0x00000001a28ddedc -[FBSSerialQueue _queue_performNextIfPossible] + 404
41  FrontBoardServices            	0x00000001a28de404 -[FBSSerialQueue _performNextFromRunLoopSource] + 28
42  CoreFoundation                	0x000000019d7b1090 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
43  CoreFoundation                	0x000000019d7b0fe8 __CFRunLoopDoSource0 + 80
44  CoreFoundation                	0x000000019d7b0780 __CFRunLoopDoSources0 + 180
45  CoreFoundation                	0x000000019d7ab8cc __CFRunLoopRun + 1080
46  CoreFoundation                	0x000000019d7ab16c CFRunLoopRunSpecific + 464
47  GraphicsServices              	0x00000001a75e3328 GSEventRunModal + 104
48  UIKitCore                     	0x00000001a1815d0c UIApplicationMain + 1936
```

**Comment by parfeon** [comment]
@EgorSobko it will be great to have symbolicated version, to be sure about location of code, which cause troubles.

**Comment by EgorSobko** [comment]
@parfeon I can tell you the stack trace that I saw in xcode:
PNPublishSequence.m -> `- (void)handleContextTransition:(NSNotification *)notification` -> `[self saveToPersistentStorage];` -> `pn_lock_async` -> `_pn_lock_async` -> `dispatch_semaphore_wait`.

The thing is, there's no crash in Debug mode, cause Watchdog waits enough.

**Comment by parfeon** [comment]
@EgorSobko it is strange, that it set semaphore as latest, because `dispatch_semaphore_wait` configured to wait **1 second**, it won't wait infinitely.

**Comment by EgorSobko** [comment]
@parfeon `pn_lock_async ` lock the main thread, then work in the block is performed, even though it is async, we wait until it finishes, only after performed work in the block:
```
// Perform data maniupulation only if PubNub client, for which manager has been created, still 
        // available. 
        if (self.client != nil) {
            
            [PNKeychain valueForKey:kPNPublishSequenceDataKey withCompletionBlock:^(NSDictionary *sequences) {
                
                NSMutableDictionary *mutableSequences = [(sequences?: @{}) mutableCopy];
                NSMutableDictionary *sequenceData = [(mutableSequences[self.publishKey]?: @{}) mutableCopy];
                sequenceData[PNPublishSequenceData.sequence] = @(self.sequenceNumber);
                sequenceData[PNPublishSequenceData.lastSaveDate] = @([NSDate date].timeIntervalSince1970);
                mutableSequences[self.publishKey] = sequenceData;
                [PNKeychain storeValue:mutableSequences forKey:kPNPublishSequenceDataKey
                   withCompletionBlock:^(BOOL stored) { completion(); }];
            }];
        }
```
is done lock is released and main thread is ready to execute.

**Comment by parfeon** [comment]
@EgorSobko `pn_lock_async` is able to lock maximum for **1 second**. 
`valueForKey: withCompletionBlock:` access Keychain (if available) on same thread, from which it has been called.
`storeValue:forKey:` - this one call asynchronously write to Keychain (if enabled).

> even though it is async, we wait until it finishes, only after performed work in the block
Indeed, it will wait for **1 second** since no one is locking main thread.

From crash, I don't see attempt to return back to foreground. I even wonder now on whether it can be part of iOS13 changes in security, which prevent Keychain access while in background.

**Comment by EgorSobko** [comment]
> From crash, I don't see attempt to return back to foreground. I even wonder now on whether it can be part of iOS13 changes in security, which prevent Keychain access while in background.

This crash is indeed happens only on iOS 13.

**Comment by EgorSobko** [comment]
@parfeon Btw, about 1 second, maybe I'm confusing myself, but what happens, imagine that `[self saveToPersistentStorage];` is called twice with delay of 1-2 seconds. What happens, MainThread -. lock is acquired -> block operation performs....... AND there another call on main thread, lock is already acquired, so main thread is blocked, waiting until block operation is finished after the first call. Am I right? Could you please advice?

**Comment by parfeon** [comment]
@EgorSobko Main thread can be locked with single call maximum for **1 second** which is used to setup `dispatch_semaphore_wait `.
Depending from deployment target, various types of lock used (hope in v5 will get rid of them): **OSSpinLock** and **os_unfair_lock**. `lock`/`unlock` here works as semaphore, so if lock already acquired, next one who is trying will have to wait, till lock will be released.
In client code the one, who really lock thread (it can be any thread, from which it has been called) is `dispatch_semaphore`, but it will be released within **1 second**. 

So, if there will be sequential calls, each of them should release _current thread_ after **1 second** delay.

**Comment by EgorSobko** [comment]
> next one who is trying will have to wait, till lock will be released.

That's what I'm talking about. Main thread acquires a lock, proceeds to work in block, then once again method is called and main thread once again tries to acquire lock, but latter is already locked. So main thread waits.

**Comment by parfeon** [comment]
@EgorSobko watchdog says, that springboard didn't responded for 10 seconds... I see only one entry to background, so it is not the case which you try to describe + it will complete earlier than 1 second, because write operation is pretty fast actually.

Today, if update will reach us, I will update all developer tools and device to give it a try to check whether there is any new capabilities options in project settings, which may prevent access to Keychain in background (simplest search only have me information about iCloud Keychain).

**Comment by EgorSobko** [comment]
@parfeon After some heavy research I found what is the real issue, please take a look at the diff. When client is nil, completion block was not called and it took 1 sec to wait method being finished. The issue became more severe because we have around 3-4 instances of this PNPublishSequence class. some of them didn't have client and so on each notification some instances blocked the main thread for 1 second each. 

After this fix, everything is perfect.

**Comment by parfeon** [comment]
@EgorSobko thanks for update! 

Looks like we never had anyone asked about it, because most people used one / two instances at once, but those use same `publish` key. This line tries to reuse existing publish sequence manager: https://github.com/pubnub/objective-c/blob/master/PubNub/Data/Managers/PNPublishSequence.m#L232 

How many `publish`/`subscribe` keys used in your application?

**Comment by EgorSobko** [comment]
@parfeon We use 2 keys, but is this really matters? When `PNPublishSequence ` is inited it is subscribed to 2 notifications which arrive to the instance independently from the client code you have mentioned.

**Comment by PetrPrazak** [comment]
I think it would be even better not to lock when there's no client, right?
Just I suggested here: https://github.com/pubnub/objective-c/pull/406

**Comment by parfeon** [comment]
@PetrPrazak actually I thought to remove that condition at all and always save data.

**Comment by PetrPrazak** [comment]
Yes, that would work too.

Btw, checking the code of `saveToPersistentStorage`, doesn't it assume there's only one client?
I guess the keychain key would be overwritten by every existing sequence manager, wouldn't it?

**Comment by parfeon** [comment]
@PetrPrazak no, https://github.com/pubnub/objective-c/blob/master/PubNub/Data/Managers/PNPublishSequence.m#L312 - here we get value for specific client (using it's `publish` key and only one `PNPublishSequence` instance exists for key).

I'm making changes to not lock, if there is no changes in sequence number since last save + performance fix from @EgorSobko (sadly, but release flow require some feature/fix branches cycle). This probably will be on next week with more changes (if nothing will change in schedule).

@EgorSobko I wanted to ask use case about two separate `publish`/`subscribe` keyset usage in single application. What is use case? Messages sent with one `publish` key won't be available from another keyset. 

If there is some tricky logic, I can suggest to ask support@pubnub.com for assistance, since they acknowledged with a lot of use cases and how they can be solved.

**Comment by PetrPrazak** [comment]
yes, but here https://github.com/pubnub/objective-c/blob/master/PubNub/Data/Managers/PNPublishSequence.m#L316 it's all saved to the same key, isn't it?

**Comment by parfeon** [comment]
@PetrPrazak with https://github.com/pubnub/objective-c/blob/master/PubNub/Data/Managers/PNPublishSequence.m#L309 we get dictionary, where each key is separate PubNub instance `subscribe` key. Modify value for PubNub client, for which `PNPublishSequence` instance created and put it back into dictionary which hold information for all clients. 
https://github.com/pubnub/objective-c/blob/master/PubNub/Data/Managers/PNPublishSequence.m#L316 - store modified dictionary under the key, which stored sequence numbers of multiple clients.

**Comment by parfeon** [comment]
Fix has been done with #414 and already released with #416 as 4.11.0 and available with CocoaPods.

**Pull request closed without merging**
