### PR TITLE
Fix YAML Validation error

### PR DESCRIPTION
**Pull request by samiahmedsiddiqui**

### CODE REVIEW

**Comment by parfeon** [comment]
@samiahmedsiddiqui YAML syntax pass validation (any validation tool confirm this).

As I understand latest version didn’t appeared in change log, because `,` in release date for change log templates was after day, not month name: `9, Mar 20`, but it should be `9 Mar, 20`.
For will be pushed along another stability fix.

**Comment by samiahmedsiddiqui** [comment]
> @samiahmedsiddiqui YAML syntax pass validation (any validation tool confirm this).

@parfeon I am using this tool for YAML verification.
https://codebeautify.org/yaml-validator

**Comment by parfeon** [comment]
I’m using this one: http://www.yamllint.com/

In addition, specs allow multi line string, when it is inside of double quotes: https://yaml.org/spec/1.2/spec.html#style/flow/double-quoted

Was there error reported by change log generator around line, which suggested in this fix?

**Comment by samiahmedsiddiqui** [comment]
@parfeon I am getting the error while parsing the YML file from Drupal. It is not reporting what the error is. I have just validated YML from an online tool and found this issue.

**Comment by parfeon** [comment]
Got it. Thanks!

Will ensure, that scripts won't make this anymore and mark this for deployment.

**Comment by samiahmedsiddiqui** [comment]
@parfeon We are still getting YML error.
Screen Shot 2020-03-26 at 11 44 10 AM

**Pull request closed without merging**
