### PR TITLE
Updated CocoaLumberjack dependency to ~> 2.0.0

### PR DESCRIPTION
**Pull request by bamse16**
Also I'd suggest to rename this repo from objective-c to pubnub-objective-c.

### CODE REVIEW

**Comment by pubnubcraig** [comment]
but it's in a repo called "pubnub". the pubnub prefix is redundant.

**Comment by bamse16** [comment]
When the user is pubnub, yes. But when you fork the repo, you only get 'objective-c', so my fork is bamse16/objective-c instead of bamse16/pubnub-objective-c.

Regards,
Marius

**Comment by pubnubcraig** [comment]
I see your point but then we'd have to rename all of our SDKs (70+).

**Comment by pubnubcraig** [comment]
I just googled "github renaming fork" and there seems to be some options
out there. Maybe explore those. There maybe drawbacks but not sure as I
just did a very quick read of the SO q's and a's.

**Comment by jzucker2** [comment]
Yes, by default git (not GitHub!) names a fork after the parent directory. But you can easily call it anything you want. `git clone https://github.com/pubnub/objective-c crazy-fork-name` And problem is solved!

**Comment by stephenlb** [comment]
👍

On Thu, Jul 30, 2015 at 9:41 AM, Jordan Zucker <notifications@github.com>
wrote:

> Yes, by default git (not GitHub!) names a fork after the parent directory.
> But you can easily call it anything you want. git clone
> https://github.com/pubnub/objective-c crazy-fork-name And problem is
> solved!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pubnub/objective-c/pull/136#issuecomment-126397405>.
>



-- 
Cheers!
Stephen Blum - CTO PubNub
http://twitter.com/stephenlb
https://github.com/pubnub - GitHub
www.pubnub.com
+1-425-830-6711

**Comment by jzucker2** [comment]
Appreciate the podspec syntax feedback. We actually merge into "develop" before "master" so that our installed pods match our current HEAD of "master". So I'm going to address this in an already open PR.

Feel free to follow along here:
https://github.com/pubnub/objective-c/pull/135

**Pull request closed without merging**
