### PR TITLE
Adding support for Swift Package Manager

### PR DESCRIPTION
**Pull request by heyzooi**

### CODE REVIEW

**Comment by parfeon** [comment]
At this moment we already have SDK written for [Swift](https://github.com/pubnub/swift).

**Comment by abhi21git** [comment]
@parfeon I have Pubnub objc installed from pods, now when I switch to SPM, I get error `Cannot find PNEventsListener in scope`, and all the methods defined in `PNEventsListener` are throwing same error

**Comment by parfeon** [comment]
@abhi21git @heyzooi this task appeared in our backlog and will be done soon.

**Comment by parfeon** [comment]
Downside of this approach is that Swift requires all headers to be added under `include`, which will lead to public interface be filled with methods from private extensions.

**Pull request closed without merging**
