### PR TITLE
Fixes for latest Cocoapods when built as dynamic framework for Swift

### PR DESCRIPTION
**Pull request by alexanderjarvis**
This fixes compilation and runtime issues when trying to use PubNub in the latest Cocoapods because it is build as a module / dynamic framework.

### CODE REVIEW

**Comment by geremyCohen** [comment]
@alexanderjarvis we'll be functionally implementing this shortly, targeting our next release. Thanks for the pull request!

**Comment by alexanderjarvis** [comment]
This still isn't fixed and in the new version it actually fails because of a new introduced zlib import in one of the private headers.

There needs to be an update to the podspec which defines the public headers as explained in http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/

**Comment by vosovets** [comment]
Hi Alexander,

Thank you for your notices.
We'll apply update with fixes in the next version.

Best Regards,
Vadim

**Comment by alexanderjarvis** [comment]
Thanks,

I fixed it on my fork by amending the podspec.

**Comment by alexanderjarvis** [comment]
Also worth noting is that the new cocoapods --pre (beta version) adds the private headers declaration from the Podspec to the generated modulemap so you don't get a warning.

**Comment by vosovets** [comment]
@alexanderjarvis Thank you for all information. We've just released new version - 3.7.10.8. It contains your pull request.

**Comment by alexanderjarvis** [comment]
Awesome, thanks!

**Pull request closed without merging**
