### PR TITLE
Silence Xcode 8.3.2 warnings for wrong param names in inline docs

### PR DESCRIPTION
**Pull request by mouhcine**

### CODE REVIEW

**Comment by Gerst20051** [comment]
👍 thanks, I was just about to open an issue.

screenshot 2017-05-01 18 23 04

**Comment by Gerst20051** [comment]
can we get this into the next release please!

**Comment by parfeon** [comment]
@mouhcine thanks for your PR. Will it be possible to create it against develop branch?

Thanks!

**Comment by mouhcine** [comment]
@parfeon I opened #330 . Closing this one.

**Pull request closed without merging**
